# Generated by Django 3.1.6 on 2021-02-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.IntegerField(db_column='github_id', primary_key=True, serialize=False, verbose_name='github user id')),
                ('login', models.CharField(db_column='github_login', max_length=39, unique=True, verbose_name='github login username')),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'github_user',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GithubRepository',
            fields=[
                ('id', models.IntegerField(db_column='github_id', primary_key=True, serialize=False, verbose_name='github repository id')),
                ('full_name', models.CharField(max_length=140, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='github_data.githubuser')),
            ],
            options={
                'verbose_name_plural': 'github repositories',
                'db_table': 'github_repository',
                'ordering': ['id'],
            },
        ),
    ]
